### ISSUE TITLE
That purple!

### ISSUE THREAD

**Issue by nootrope** [dcmk1mr2/ebarc-org#33]
It's very ugly as a background color. Backgrounds should not fight the foreground for signal. Are you sure you want that hue? It also flunks accessibility tests. I recommend using the [Material Design Color Tool](https://material.io/color/#!/?view.left=0&view.right=0) to come up with a good palette that takes into account legibility.

**Comment by dcmk1mr2** [comment]
Like I said I'm pretty bad with color in general.  The scheme came from https://material.io/color/#!/?view.left=0&view.right=0&primary.color=6200EA

**Comment by nootrope** [comment]
Did you check the ACCESSIBILITY tab while in that tool? :)

**Comment by dcmk1mr2** [comment]
I just discovered that tool.

**Comment by nootrope** [comment]
It's a tough problem, getting a good palette. Do(es) any color(s) exemplify amateur radio or EBARC to you?

**Comment by nootrope** [comment]
@dcmk1mr2: New purple looks a LOT better! Closing this issue.
