### ISSUE TITLE
More styling

### ISSUE THREAD

**Issue by dcmk1mr2** [dcmk1mr2/ebarc-org#9]
How to make the entire BOD table fit.  I needed to change it and managed to hose it

**Comment by nootrope** [comment]
If you look at your [latest entry](https://github.com/dcmk1mr2/ebarc-org/commit/0f1c4e3fa96ebc22b30aa6eb9f79083663a13d96#diff-fb8a140d6f076647256a4ea161f4c280) into the commit history, you'll see the—sometimes significant—stuff you deleted, marked in red. In this case, you deleted the CSS selector class, `ebarc-bod` from the `iframe` element, which might help later. More significantly, you deleted the `width=` and `height=` attributes from the same.

Looks like you embedded a new sheet, forked from the one I originally shared. If you share it with me I can adjust things a bit more for readability. The idea was that you change the originally shared sheet (at Google Sheets) and the changes would update in its embedded view.

**Comment by nootrope** [comment]
I fixed this issue and committed the changes. Be sure to `git pull` and check its history for the howto.
